# Generated by Django 3.2.16 on 2022-12-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='shelf',
        ),
    ]
