# Generated by Django 3.2.16 on 2023-01-09 13:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_auto_20221230_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
