# Generated by Django 3.2.16 on 2023-01-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(default='https://res.cloudinary.com/dzg7yacrw/image/upload/v1673273165/assets/book_covers/cover_placeholder_vqd1hn.jpg'),
        ),
    ]
