# Generated by Django 3.2.16 on 2023-01-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0005_book_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
    ]
