# Generated by Django 3.2.16 on 2023-01-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0006_remove_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fan', 'Fantasy'), ('adv', 'Adventure'), ('rom', 'Romance'), ('dys', 'Dystopian'), ('mys', 'Mystery'), ('hor', 'Horror'), ('thrill', 'Thriller'), ('hisfic', 'Historical Fiction'), ('scifi', 'Science Fiction'), ('bio', 'Biography'), ('cook', 'Cookbook'), ('mot', 'Motivational'), ('health', 'Health'), ('his', 'History'), ('travel', 'Travel'), ('diy', 'How-to')], max_length=6),
        ),
    ]
